$(function(){
	//attr('ok');0：失败；1：成功；2：默认
	//attr('ready');0：失败；1：成功
	$('#username').attr('ok','0');
	$('#password').attr('ok','0');
	$('#checkpassword').attr('ok','0');
	$('#verify_input').attr('ok','0');
	$('#phone').attr('ok','0');
	$('#obtain').attr({'ok':'2','ready':'0'});
	$('#checkphone').attr('ok','0');
	$('#form_cbox').attr('ok','0');
	$('#form_sub').attr('ok','0');
	$('#form_sub').addClass('submit_false');
	/*-------------------------------------------username------------------------------------------*/
	$('#username').blur(function(){
		$('#username').attr('ok','0');
		if($('#username').val().length>0){
			var reg = /^[a-zA-Z][0-9a-zA-Z]{1,15}$/;
			var eml = $('#useremail option:selected').val();
			if(reg.test($('#username').val())){
				$.ajax({
					type:"get",
					url:"/project/guestbook/index.php",
					async:true,
					data:{
						'm':'index',
						'a':'verifyUserName',
						'username':$('#username').val()+eml
					},
					success:function(str){
						var json = JSON.parse(str);
//						console.log(str);
						$('#username_icon').parent().show();
						$('#username_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
						if(json.code==0){
							$('#username_icon').addClass('tips_icon_success');
							$('#username').attr('ok','1');
							checkAll();
						}
						else{
							$('#username_icon').addClass('tips_icon_error');
							$('#username').addClass('form_input_red');
						}
						$('#username_info').html(json.message);
					},
					error:function(){
						alert('ajax请求失败！');
					}
				});
			}
			else{
				$('#username_icon').parent().show();
				$('#username_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
				$('#username_icon').addClass('tips_icon_error');
				$('#username').addClass('form_input_red');
				var size = $('#username').val().length;
				if(size<6||size>18){
					$('#username_info').html('帐号须由6-18个字符组成');
				}
				else{
					$('#username_info').html('帐号由字母开头，用字母、数字或下划线命名');
				}
			}
		}
		else{
			$('#username_icon').parent().hide();
		}
	}).bind('input propertychange', function() {
	    if($('#username').val().length>0){
			$('#username_empty').parent().show();
		}
		else{
			$('#username_empty').parent().hide();
		}
	}).focus(function(){
		$('#username').removeClass('form_input_red');
	});
	$('#username_empty').click(function(){
		$(this).parent().hide();
		$('#username').val('').blur().focus();
	});
	
	/*-------------------------------------------password------------------------------------------*/
	$('#password').blur(function(){
		$('#password').attr('ok','0');
		var size = $('#password').val().length;
		if(size>0){
			$('#password_icon').parent().show();
			$('#password_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
			if(size<6||size>16){
				$('#password_icon').addClass('tips_icon_error');
				$('#password').addClass('form_input_red');
				$('#password_info').html('密码须由6-16个字符组成，区分大小写');
			}
			else{
				$('#password').removeClass('form_input_red');
				$('#password_icon').addClass('tips_icon_success');
				$('#password_info').html('');
				$('#password').attr('ok','1');
				checkAll();
			}
		}
		else{
			$('#password_icon').parent().hide();
		}
	}).bind('input propertychange', function() {
	    if($('#password').val().length>0){
			$('#password_empty').parent().show();
		}
		else{
			$('#password_empty').parent().hide();
		}
	}).focus(function(){
		$('#password').removeClass('form_input_red');
	});
	$('#password_empty').click(function(){
		$(this).parent().hide();
		$('#checkpassword').val('').blur().focus();
		$('#password').val('').blur().focus();
	});
	
	/*-------------------------------------------checkpassword------------------------------------------*/
	$('#checkpassword').blur(function(){
		$('#checkpassword').attr('ok','0');
		var size = $('#checkpassword').val().length;
		if(size>0){
			$('#checkpassword_icon').parent().show();
			$('#checkpassword_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
			if(size<6||size>16){
				$('#checkpassword_icon').addClass('tips_icon_error');
				$('#checkpassword').addClass('form_input_red');
				$('#checkpassword_info').html('密码须由6-16个字符组成，区分大小写');
			}
			else{
				if($('#checkpassword').val()!=$('#password').val()){
					$('#checkpassword_icon').addClass('tips_icon_error');
					$('#checkpassword').addClass('form_input_red');
					$('#checkpassword_info').html('密码不一致');
				}
				else{
					$('#checkpassword').removeClass('form_input_red');
					$('#checkpassword_icon').addClass('tips_icon_success');
					$('#checkpassword_info').html('');
					$('#checkpassword').attr('ok','1');
					checkAll();
				}
			}
		}
		else{
			$('#checkpassword_icon').parent().hide();
		}
	}).bind('input propertychange', function() {
	    if($('#checkpassword').val().length>0){
			$('#checkpassword_empty').parent().show();
		}
		else{
			$('#checkpassword_empty').parent().hide();
		}
	}).focus(function(){
		$('#checkpassword').removeClass('form_input_red');
	});
	$('#checkpassword_empty').click(function(){
		$(this).parent().hide();
		$('#checkpassword').val('').blur().focus();
	});
	
	/*-------------------------------------------verify------------------------------------------*/
	var verify_num = Math.round(Math.random()*9999);
	if(verify_num<1000){
		if(verify_num<100){
			if(verify_num<10){
				verify_num='0'+verify_num;
			}
			verify_num='0'+verify_num;
		}
		verify_num='0'+verify_num;
	}
	$('#verify_num').html(verify_num);
	$('#verify_input').blur(function(){
		$('#verify_input').attr('ok','0');
		var size = $('#verify_input').val().length;
		if(size>0){
			$('#verify_icon').parent().show();
			$('#verify_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
			if($('#verify_input').val()!=verify_num){
				$('#verify_icon').addClass('tips_icon_error');
				$('#verify_input').addClass('form_input_red');
				$('#verify_info').html('验证码错误');
			}
			else{
				$('#verify_input').removeClass('form_input_red');
				$('#verify_icon').addClass('tips_icon_success');
				$('#verify_info').html('');
				$('#verify_input').attr('ok','1');
				checkAll();
			}
		}
		else{
			$('#verify_icon').parent().hide();
		}
	}).focus(function(){
		$('#verify_input').removeClass('form_input_red');
	});
	
	/*-------------------------------------------phone------------------------------------------*/
	$('#phone').blur(function(){
		$('#phone').attr('ok','0');
		var size = $('#phone').val().length;
		if(size>0){
			$('#phone_icon').parent().show();
			$('#phone_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
			if($('#phone').val().length!=11){
				$('#phone_icon').addClass('tips_icon_error');
				$('#phone').addClass('form_input_red');
				$('#phone_info').html('请输入正确的手机号');
				$('#phone_info').addClass('form_error_red');
				$('#obtain').addClass('obtainphone_false');
			}
			else{
				$.ajax({
					type:"get",
					url:"http://apis.juhe.cn/mobile/get",
					async:true,
					data:{
						'phone':$('#phone').val(),
						'key':'445cb26914fdcc84571bd02719ef6ebe',
						'dtype':'json'
					},
					dataType:'jsonp',
					jsonp:'callback',
					success:function(str){
//						console.log(str);
						if(str.resultcode!=200){
							$('#phone_icon').addClass('tips_icon_error');
							$('#phone').addClass('form_input_red');
							$('#phone_info').html('请输入正确的手机号');
							$('#phone_info').addClass('form_error_red');
							$('#obtain').attr({'ok':'0'});
						}
						else{
							var data = str.result;
							$('#phone').removeClass('form_input_red');
							$('#phone_icon').addClass('tips_icon_success');
							$('#phone_info').html(data.province+data.city+data.company).removeClass('form_error_red');
							$('#phone').attr('ok','1');
							$('#obtain').removeClass('obtainphone_false');
							$('#obtain').attr({'ok':'1'});
							checkAll();
						}
					},
					error:function(){
						alert('ajax请求失败！');
					}
				});
			}
		}
		else{
			$('#phone_icon').parent().hide();
		}
	}).focus(function(){
		$('#phone').removeClass('form_input_red');
	}).bind('input propertychange', function() {
	    if($('#phone').val().length>0){
			$('#phone_empty').parent().show();
		}
		else{
			$('#phone_empty').parent().hide();
		}
	}).focus(function(){
		$('#phone').removeClass('form_input_red');
	});
	$('#phone_empty').click(function(){
		$(this).parent().hide();
		$('#phone').val('').blur().focus();
	});
	
	
	/*-------------------------------------------checkphone------------------------------------------*/
	$('#obtain').click(function(){
		if($('#obtain').attr('ok')==1){
			$('#obtain').attr({'ok':'0','ready':'1'});
			$('#obtain').addClass('obtainphone_false');
			var time=30;
			var interval = setInterval(function(){
				if(time==0){
					clearInterval(interval);
					$('#obtain').val('获取验证码');
					$('#obtain').attr('ok','1');
					$('#obtain').removeClass('obtainphone_false');
					checkAll();
				}
				else{
					$('#obtain').val(time+'秒');
					time--;
				}
				
			},100);
		}
		else{
			return false;
		}
	});
	$('#checkphone').blur(function(){
		var reg = /^[0-9]{6}$/;
		if($('#checkphone').val().length>0){
			$('#checkphone_icon').parent().show();
			$('#checkphone_icon').removeClass('tips_icon_success').removeClass('tips_icon_error');
			if(reg.test($('#checkphone').val())){
				$('#checkphone').removeClass('form_input_red');
				$('#checkphone_icon').addClass('tips_icon_success');
				$('#checkphone_info').html('');
				$('#checkphone').attr('ok','1');
				checkAll();
			}
			else{
				$('#checkphone_icon').addClass('tips_icon_error');
				$('#checkphone').addClass('form_input_red');
				$('#checkphone_info').html('验证码错误');
				$('#checkphone_info').addClass('form_error_red');
				$('#checkphone').attr('ok','0');
			}
		}
		else{
			$('#checkphone_icon').parent().hide();
		}
	}).bind('input propertychange', function() {
	    if($('#obtain').attr('ready')==0){
	    	$('#checkphone').val('');
		}
	});
	
	
	/*-------------------------------------------checkbox------------------------------------------*/
	$('#form_cbox').click(function(){
		if($('#form_cbox').attr('ok')==0){
			$(this).attr('ok','1').addClass('checktips_cbox_ok');
			checkAll();
		}
		else{
			$(this).attr('ok','0').removeClass('checktips_cbox_ok');
		}
	});
	
	function checkAll(){
		if($('#username').attr('ok')==1&&
		$('#password').attr('ok')==1&&
		$('#checkpassword').attr('ok')==1&&
		$('#verify_input').attr('ok')==1&&
		$('#phone').attr('ok')==1&&
		$('#checkphone').attr('ok')==1&&
		$('#form_cbox').attr('ok')==1
		){
			$('#form_sub').removeClass('submit_false');
			$('#form_sub').attr('ok','1');
		}
		else{
			$('#form_sub').addClass('submit_false');
			$('#form_sub').attr('ok','0');
		}
	}
	/*-------------------------------------------submit------------------------------------------*/
	$('#form_sub').click(function(){
		if($('#form_sub').attr('ok')==1){
			var eml = $('#useremail option:selected').val();
			$.ajax({
				type:"post",
				url:"/project/guestbook/index.php",
				async:true,
				data:{
					'm':'index',
					'a':'reg',
					'username':$('#username').val()+eml,
					'password':$('#password').val()
				},
				success:function(str){
					$('#register_form').hide();
					$('.regsuccess').show();
					$('#banner_img').attr('src','img/register_bannerbig.png');
				},
				error:function(){
					alert('ajax请求失败！');
				}
			});
		}
		else{
			return false;
		}
	});
});
